#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔃 husky pre-commit starting."
lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents
echo "✅ husky pre-commit complete."
